// Generated by scripts/gen-ba-manifest.sh from the installed models; do not edit.
// The same manifest as speech-model-manifest.json, compiled in so every target carries it.

extension ModelManifest {
    static let shipped = ModelManifest(
        repo: "fcttechnologies/fctspeech-coreml",
        assets: [
            ModelAsset(path: "parakeet-v3/ParakeetDecoder.mlmodelc/analytics/coremldata.bin", size: 243),
            ModelAsset(path: "parakeet-v3/ParakeetDecoder.mlmodelc/coremldata.bin", size: 464),
            ModelAsset(path: "parakeet-v3/ParakeetDecoder.mlmodelc/model.mil", size: 14933),
            ModelAsset(path: "parakeet-v3/ParakeetDecoder.mlmodelc/weights/weight.bin", size: 24441152),
            ModelAsset(path: "parakeet-v3/ParakeetEncoder.mlmodelc/analytics/coremldata.bin", size: 243),
            ModelAsset(path: "parakeet-v3/ParakeetEncoder.mlmodelc/coremldata.bin", size: 421),
            ModelAsset(path: "parakeet-v3/ParakeetEncoder.mlmodelc/model.mil", size: 684357),
            ModelAsset(path: "parakeet-v3/ParakeetEncoder.mlmodelc/weights/weight.bin", size: 460727232),
            ModelAsset(path: "parakeet-v3/ParakeetJoint.mlmodelc/analytics/coremldata.bin", size: 243),
            ModelAsset(path: "parakeet-v3/ParakeetJoint.mlmodelc/coremldata.bin", size: 450),
            ModelAsset(path: "parakeet-v3/ParakeetJoint.mlmodelc/model.mil", size: 4639),
            ModelAsset(path: "parakeet-v3/ParakeetJoint.mlmodelc/weights/weight.bin", size: 10510028),
            ModelAsset(path: "parakeet-v3/pieces.json", size: 115741),
            ModelAsset(path: "sensevoice/SenseVoice.mlmodelc/analytics/coremldata.bin", size: 243),
            ModelAsset(path: "sensevoice/SenseVoice.mlmodelc/coremldata.bin", size: 462),
            ModelAsset(path: "sensevoice/SenseVoice.mlmodelc/model.mil", size: 975495),
            ModelAsset(path: "sensevoice/SenseVoice.mlmodelc/weights/weight.bin", size: 468342782),
            ModelAsset(path: "sensevoice/pieces.json", size: 251841),
            ModelAsset(path: "sortformer/Sortformer.mlmodelc/analytics/coremldata.bin", size: 243),
            ModelAsset(path: "sortformer/Sortformer.mlmodelc/coremldata.bin", size: 541),
            ModelAsset(path: "sortformer/Sortformer.mlmodelc/model.mil", size: 1131053),
            ModelAsset(path: "sortformer/Sortformer.mlmodelc/weights/weight.bin", size: 234906752),
        ])
}
